name: CheckLinks

# run on pushes and pull requests to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# run job
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    # checkout repository
    - name: Checkout-repository
      uses: actions/checkout@v2
    # check links in html folder
    - name: Link checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -d book/website -r book/website
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
