name: CI

# run on pushes and pull requests to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# run job
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-repository
      uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ./book/website/requirements.txt
    - name: Build Jupyter-Book
      run: |
        cd ./book/website
        jupyter-book build .
    - name: Print directory (TEST)
        cd home/runner/work/the-turing-way/the-turing-way/book/website/_build/html
        ls
    - name: Run html proofer
      uses: chabad360/htmlproofer@master
      with: 
        directory: "home/runner/work/the-turing-way/the-turing-way/book/website/_build/html"
        arguments: --allow-hash-href --assume-extension --disable-external --only_4xx

      
    # - name: Set up Node.js
    #   uses: actions/setup-node@v1
    # - name: Install remark-validate-links
    #   run: npm install remark-validate-links
    # - name: Run remark-validate-links
    #   run: remark -u validate-links book/website/
    
    # check links in markdown folder
    # - name: Markdown-link-check
    #   uses: gaurav-nelson/github-action-markdown-link-check@v1
    #   with:
    #     use-quiet-mode: 'yes'
    #     folder-path: book/website
    #     file-extension
    # - name: Link checker
    #   id: lc
    #   uses: peter-evans/link-checker@v1
    #   with:
    #     args: -d book/website -r book/website
    # - name: Fail if there were link errors
    #   run: exit ${{ steps.lc.outputs.exit_code }}
