# Give your test a name!
name: ContributorsRecord

# runs daily
on:
  schedule:
    - cron:  '30 23 * * *'
    # minute (0 - 59), hour (0 - 23), day of month (1 - 31), month(1 - 12 or JAN-DEC), day of week (0 - 6 or SUN-SAT)

# Set up the Continuous Integration job
jobs:
  ContributorsRecord:
    runs-on: ubuntu-latest
    # This section collects together the steps involved in running the test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      # Run a simple script that combines content from 2 files
      - name: Combine contributors.md and contributors table
        run: |
          chmod +x ./tests/contributors.sh
          ./tests/contributors.sh

      # Run git steps for add, commit, push changes
      - name: git commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./book/website/afterword/contributors-record.md
          git commit -am 'automated update of Contributors Record'
          git push

      # Create a PR with changes
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ secrets.INTERMEDIATE_BRANCH }} # If blank, default: triggered branch
          destination_branch: "master" # If blank, default: master
          pr_title: "Update Contributors Record in Afterword" # Title of pull request
          pr_body: ":crown: *An automated PR*"
          pr_label: "automated-pr"
          github_token: ${{ secrets.GITHUB_TOKEN }}
