# Give your test a name!
name: ContributorsRecord

# runs weekly - testing for per minute
on:
  schedule:
    - cron:  '*/1 * * * *'
    # minute (0 - 59), hour (0 - 23), day of month (1 - 31), month(1 - 12 or JAN-DEC), day of week (0 - 6 or SUN-SAT)

# Set up the Continuous Integration job
jobs:
  ContributorsRecord:
    runs-on: ubuntu-latest
    # This section collects together the steps involved in running the test
    steps:
      - name: Checkout branch for Pull Requesting to GitHub
        uses: actions/checkout@v2
      - name: Combine contributors.md and contributors table
        run: |
          ./tests/contributors.sh
      - name: Add contributors-record.md to Afterword and commit changes
        run: |
          git add ./book/website/afterword/contributors-record.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am 'authomated update of Contributors Record'
          git push
