# Give your test a name!
name: TestCron

# runs daily
on:
  schedule:
    - cron: '*/2 * * * *'
    # minute (0 - 59), hour (0 - 23), day of month (1 - 31), month(1 - 12 or JAN-DEC), day of week (0 - 6 or SUN-SAT)

# Set up the Continuous Integration job
jobs:
  TestCron:
    runs-on: ubuntu-latest
    # This section collects together the steps involved in running the test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      # Run a simple script that combines content from 2 files
      - name: Combine contributors information
        run: |
          chmod +x ./tests/contributors.sh
          ./tests/contributors.sh
